### ISSUE TITLE
Q: How to include font-awesome.scss styles

### ISSUE THREAD

**Issue by sohailalam2** [crisbal/vue-webpack-ssr-fully-featured#6]
First of all, thanks a lot @crisbal for this awesome skeleton. This is exactly what I have been looking for. Great work!! 💯 

I have used Nuxt and its really easy to add external css/scss dependencies to the nuxt.config.js file. However, since we do not have such a config file here, I assume we need to add those dependencies to the `src/styles/global.scss` file. So I did, and it works perfectly for Bulma. But as soon as I do it for font-awesome, things break and the build process fails. 

**FYI, bulma and font-awesome are installed as npm dependencies and are included from the node_modules.**

I tried overriding the font-awesome variable `$fa-font-path: '~node_modules/font-aweome/fonts';` to find the correct path for the fonts/ directory, but cant figure out what should be correct value for it to work. 

Am I missing something here? How can I achieve this?

```scss
@import 'declarations';
@import '~font-awesome/scss/font-awesome';
@import '~bulma/bulma.sass';

* {
	box-sizing: border-box;
	margin: 0;
	padding: 0;
}

body {
	font-family: sans-serif;
}

.view {
	padding: 1rem;
}

```

```sh
$ npm run dev

> vue-webpack-ssr-fully-featured@0.0.5 dev D:\vue-webpack-ssr-fully-featured
> node server

Server started at localhost:8080
webpack building...


 ERROR  Failed to compile with 6 errors                                                                                                                                                      12:28:27

These relative modules were not found:

* ../fonts/fontawesome-webfont.eot in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../fonts/fontawesome-webfont.eot?v=4.7.0 in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../fonts/fontawesome-webfont.svg?v=4.7.0 in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../fonts/fontawesome-webfont.ttf?v=4.7.0 in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../fonts/fontawesome-webfont.woff2?v=4.7.0 in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../fonts/fontawesome-webfont.woff?v=4.7.0 in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-89630dc8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue

D:\vue-webpack-ssr-fully-featured\node_modules\memory-fs\lib\MemoryFileSystem.js:107
                        throw new MemoryFileSystemError(errors.code.ENOENT, _path);
                        ^
Error
    at MemoryFileSystem.readFileSync (D:\vue-webpack-ssr-fully-featured\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at readFile (D:\vue-webpack-ssr-fully-featured\build\setup-dev-server.js:40:33)
    at Compiler.clientCompiler.plugin (D:\vue-webpack-ssr-fully-featured\build\setup-dev-server.js:41:31)
    at Compiler.applyPlugins (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compiler.js:104:17)
    at onCompiled (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compiler.js:54:18)
    at applyPluginsAsync.err (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compiler.js:514:14)
    at next (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (D:\vue-webpack-ssr-fully-featured\node_modules\webpack\lib\Compilation.js:662:11)
    at Compilation.applyPluginsAsyncSeries (D:\vue-webpack-ssr-fully-featured\node_modules\tapable\lib\Tapable.js:195:46)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-webpack-ssr-fully-featured@0.0.5 dev: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-webpack-ssr-fully-featured@0.0.5 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MeirionHughes** [comment]
I've had the same issue with node-open-sans, just with the vue-electron template. I would also like to know how to get webpack to resolve relative deps for scss too. 👍

**Comment by crisbal** [comment]
Hey! Thanks for opening the issue. I think I figured it out.

First of all for Bulma it just works by including:

```sass
@import "~bulma/bulma.sass";
```
 For Font-Awesome I first had to introduce support for font files in the main build script (commit 27dd04f54fa7fde439497985459d2655018f9674) and then include the CSS file instead of the SCSS one.

```sass
@import "~font-awesome/css/font-awesome.css";
```

As you can see from the screenshot now they both work.

![deepin-screenshot j13957](https://user-images.githubusercontent.com/2728038/31274399-0751e66c-aa93-11e7-8082-d83931fd0f52.png)

```pug
a.button.is-primary Hello there
i.fa.fa-home.fa-2x
```

I didn't get `font-awesome.scss` to work but I don't think that is an issue.

**Comment by crisbal** [comment]
@MeirionHughes I am not sure how to achieve relative deps resolving for sass-loader, I tested a few proposed solutions online but I did not find one that worked.
